config/routes.rb
Rails.application.routes.draw do
  resources :usuarios

  resources :medicos

  get 'static/index'

  resources :centro_saluds

  root 'static#index', as: 'static'

  get '/medic_register/:id' => 'medicos#new', as: :registro_medico
  get '/centro_register/:id' => 'centro_saluds#new', as: :registro_centro
  get '/ad%/xas/159/qw%/:id' => 'usuarios#registro_inicio', as: :phase1
  get '/oq/q2s/2/qw%/:remember_token' => 'usuarios#pre_process', as: :pre_pro
  get '/usuarios/registro_inicio'
  get '/emailcheck/:id', to: 'static#emailcheck', as: :mailcheck

  post '/sessions/' => 'sessions#create', as: :sessions
  delete '/signout/' => 'sessions#destroy', as: :sessions_destroy
  get '/error/' => 'sessions#signin_error', as: :session_error
  match '/signin', to: 'sessions#signin', via: 'get'

  get '/ajustes/:remember_token' => 'usuarios#ajustes', as: :ajustes
  get '/ajustes/mod_info_cuenta/:id' => 'usuarios#modificar_info', as: :modificar_info
  get '/austes/mod_info_cuenta/edit_nombre/:id' => 'usuarios#edit_nombre', as: :edit_nombre
  get '/mod_info_cuenta/' => 'static#info_cambiada', as: :info_cambiada

  get '/new_servicios_medicos/:id' => 'medicos#registrar_servicios_medicos', as: :registrar_servicios_medicos
  get '/servicios_medicos/:id' => 'medicos#ver_servicios_medicos', as: :ver_servicios_medicos
  get '/editar_servicios_medicos/:id' => 'medicos#editar_servicios_medicos', as: :editar_servicios_medicos

  get '/already_registered/' => 'static#already_registered', as: :already_registered

end

app/models/usuario.rb
#encoding: utf-8
class Usuario < ActiveRecord::Base
  has_many :medicos
  has_many :centro_saluds

  before_save { self.email = email.downcase }
  before_create :create_remember_token

  validates :nombre, format: {
      with: /(\A[a-zA-ZñÑáéíóúÁÉÍÓÚäëïöüÄËÏÖÜßÇç´][a-zA-ZñÑáéíóúÁÉÍÓÚßÇç´ -']+\Z)/, :message => 'El Nombre no puede contener números ni caracteres especiales'
  }
  validates :nombre, length: {in: 2..25, :message => "El Nombre no debe ser mayor a 25 caracteres" }
  validates :nombre, :presence => { :message => "El campo Nombre es obligatorio"}, on: :create

  validates :email, format: {
      with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, message: 'Inserte una direccion de correo valida'
  }
  validates :email, :presence => { :message => "El campo Email es obligatorio"}, :uniqueness => { :message => "Email ya existente"}, on: :create

  validates :password, format: {
      with: /\A^.*(?=.{4,10})(?=.*\d)(?=.*[a-zA-Z]).*\z/i, message: 'La contraseña debe de tener al menos una letra y un número y tener de 4 a 10 caracteres'
  }, on: :create, on: :create
  has_secure_password
  validates :password, :presence => { :message => "El campo Contraseña es obligatorio"}, on: :create

=begin
  validate :not_update_tipo_usuario

  def not_update_tipo_usuario
    if self.tipo_usuario!=nil
      errors.add(:tipo_usuario, "Ya tienes un Tipo de Usuario registrado")
    end
  end
=end

  def Usuario.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def Usuario.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end
  #=============================================================
  #======================== PRIVATE ============================
  private
    def create_remember_token
      self.remember_token = Usuario.digest(Usuario.new_remember_token)
    end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :show, only: [:show, :edit, :update, :destroy]
  before_action :set_user, only: [:pre_process, :ajustes]

  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.order(:email)
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
    @usuario = Usuario.find(params[:id])
    if @usuario.tipo_usuario == 1
      @medico = Medico.find_by_usuario_id(@usuario.id)
    end

    if @usuario.tipo_usuario == 2
      @centro_salud = CentroSalud.find_by_usuario_id(@usuario.id)
    end
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)
    @usuario.tipo_usuario = nil
    respond_to do |format|
      if @usuario.save
        if MailConfirm.recibido(@usuario).deliver
          format.html { redirect_to mailcheck_path(@usuario) }
          # MailConfirm.recibido(@usuario).deliver
          format.json { render :show, status: :created, location: @usuario }
        end
      else
        @usuario.errors.each do |name_, erro|
          flash[name_] = erro
        end
        format.html { redirect_to new_usuario_path }
        #format.json { render :json => { :error => @usuario.errors.full_messages }, :status => 422 }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        update_nombre_rol
        format.html { redirect_to info_cambiada_path, notice: "Usuario #{@usuario.email} fue actualizado exitosamente." }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: 'Usuario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


    # Use callbacks to share common setup or constraints between actions.
=begin
  def set_usuario
      @usuario = Usuario.find(params[:id])
   end
=end

    # Never trust parameters from the scary internet, only allow the white list through.
   def usuario_params
      params.require(:usuario).permit(:nombre, :email, :password, :password_confirmation, :remember_token)
   end
  def pre_process
    redirect_to phase1_path(@usuario.id)
  end

  def registro_inicio
    @usuario=Usuario.find(params[:id])
    if !signed_in?
      sign_in @usuario
    end
  end

  def ajustes
    if @usuario.tipo_usuario == nil
    else
      if @usuario.tipo_usuario == 1
        @medico = Medico.find_by_usuario_id(@usuario.id)
      end

      if @usuario.tipo_usuario == 2
        @centro_salud = CentroSalud.find_by_usuario_id(@usuario.id)
      end
    end
  end

  def modificar_info
    @usuario = Usuario.find(params[:id])
  end

  def edit_nombre
    @usuario = Usuario.find(params[:id])
  end

  def update_nombre_rol
    if @usuario.tipo_usuario == "1"
      @medico=Medico.find(@usuario.rol_id)
      @medico.nombre = @usuario.nombre
      @medico.save
    end
    if @usuario.tipo_usuario == "2"
      @centro_salud = CentroSalud.find(@usuario.rol_id)
      @centro_salud.nombre=@usuario.nombre
      @centro_salud.save
    end
  end

  #=============================================================
  #======================== SESSION ============================

  def Usuario.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def Usuario.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end
  #=============================================================
  #======================== PRIVATE ============================
  private
    def create_remember_token
      self.remember_token = Usuario.digest(Usuario.new_remember_token)
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @usuario = Usuario.find_by(remember_token: params[:remember_token])
    end
end

app/helpers/usuarios_helper.rb
#encoding: utf-8
module UsuariosHelper

  def not_update_tipo_usuario
    if @usuario.tipo_usuario == 1
      @usuario.errors.add("Médico", "Ya estas registrado como Médico, no te puedes volver a registrar.")
      return false
    else
      if @usuario.tipo_usuario == 2
        @usuario.errors.add("Centro de Salud", "Ya estas registrado como Centro de Salud, no te puedes volver a registrar.")
        return false
      else
        return true
      end
    end
  end
end

app/views/usuarios/_form.html.erb
<!--<% if @usuario.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-error">
        The form contains <%= pluralize(@usuario.errors.count, "error") %>.
      </div>
      <ul>
        <% @usuario.errors.full_messages.each do |msg| %>
            <li>* <%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>-->

<%- if flash.any? %>
    <%- flash.keys.each do |flash_key| %>
        <%- next if flash_key.to_s == 'timedout' %>
        <h3 style="color: #f30000; <%= flash_key %>">
          <a class="close" data-dismiss="alert" href="#"> x</a>
          <%= flash.discard(flash_key) %>
        </h3>
    <%- end %>
<%- end %>

<%= form_for @usuario, html: {class: "horizontal-form", role:"form"} do |f|  %>
  <% if signed_in? %>
        <h1>No se puede registrar nuevo usuario si se esta logueado</h1>
  <% else %>
        <h1>Registro de nuevo usuario</h1>
        <div class="form-group">
           <%= f.label :nombre, :class=>"col-sm-2 control-label" %>
          <div class="col-sm-10">
            <%= f.text_field :nombre, :class=>"form-control", :placeholder =>"Nombre" %><br>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :email, :class=>"col-sm-2 control-label" %>
          <div class="col-sm-10">
            <%= f.text_field :email, :class=>"form-control", :placeholder =>"Email" %><br>
          </div>
        </div>
        <div class="form-group">
          <%= f.label "Contraseña", :class=>"col-sm-2 control-label" %>
          <div class="col-sm-10">
            <%= f.password_field :password, :class=>"form-control", :placeholder =>"Contraseña" %><br>
          </div>
        </div>
        <div class="form-group">
          <%= f.label "Confirmar Contraseña", :class=>"col-sm-2 control-label" %>
          <div class="col-sm-10">
            <%= f.password_field :password_confirmation, :class=>"form-control", :placeholder =>"Confirmar Contraseña" %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <%= f.submit 'Registrarse', :class=>"btn btn-default" %>
          </div>
        </div>
  <% end %>
<% end %>

app/views/usuarios/ajustes.html.erb
<div class="container-full">

  <div class="row">

    <div class="col-lg-12 text-center v-center">

      <h1>Ajustes</h1>

      <br>

      <form class="col-lg-12">

      </form>
      <% if @usuario.tipo_usuario == nil %>
          <h2>No has completado tu registro, terminalo entrando en Editar Tipo de Cuenta</h2><br><br>
          <div><span class="glyphicon glyphicon-briefcase"></span>              <%= link_to "Editar Tipo de Cuenta", phase1_path(@usuario), :class => 'btn btn-default' %></div><br>
      <% else %>
          <% if @usuario.tipo_usuario == 1 %>
              <div><span class="glyphicon glyphicon-briefcase"></span>              <%= link_to "Modificar Perfíl de Médico", edit_medico_path(@medico), :class => 'btn btn-default' %></div><br>
              <div><span class="glyphicon glyphicon-list-alt"></span>              <%= link_to "Editar Servicios Médicos Ofrecidos", editar_servicios_medicos_path(@medico), :class => 'btn btn-default' %></div><br>
          <% end %>

          <% if @usuario.tipo_usuario == 2 %>
              <div><span class="glyphicon glyphicon-briefcase"></span>              <%= link_to "Modificar Información de Centro de Salud", edit_centro_salud_path(@centro_salud), :class => 'btn btn-default' %></div><br>
          <% end %>
      <% end %>


      <div><span class="glyphicon glyphicon-cog"></span>                <%= link_to "Modificar información de cuenta", modificar_info_path(@usuario), :class => 'btn btn-default' %></div></div>
     <!-- <div><span class="glyphicon glyphicon-screenshot"></span>   <%= link_to "Cambiar Nombre de Cuenta", '#', :class => 'btn btn-default' %></div><br>
      <div><span class="glyphicon glyphicon-cog"></span>   <%= link_to "Cambiar Contraseña", '#', :class=>'btn btn-default  ' %></div><br>
      <div><span class="glyphicon glyphicon-envelope"></span>   <%= link_to "Modificar Correo", '#', :class => 'btn btn-default' %></div><br>
       -->


    </div>

  </div> <!-- /row -->

  <div class="row">


  </div>

  <br><br><br><br><br>

</div>

app/views/usuarios/edit.html.erb
<h1>Editing usuario</h1>

<%= render 'form' %>

<%= link_to 'Show', @usuario %> |
<%= link_to 'Back', usuarios_path %>

app/views/usuarios/edit_nombre.html.erb
<%= form_for @usuario, html: {class: "horizontal-form", role:"form"} do |f|  %>
    <% if @usuario.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

          <ul>
            <% @usuario.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <% if !signed_in? %>
        <h1>Usted no esta logueado</h1>
    <% else %>
        <h1>Editar Nombre de Usuario</h1>
        <div class="form-group">
          <%= f.label :nombre, :class=>"col-sm-2 control-label" %>
          <div class="col-sm-10">
            <%= f.text_field :nombre, :class=>"form-control" %><br>
          </div>
        </div>
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <%= f.submit 'Guardar Cambios',:class=>"btn btn-default", data: { confirm: 'Seguro que desea guardar los cambios?' } %>
          </div>
        </div>
    <% end %>
<% end %>

app/views/usuarios/index.html.erb
<h1>Listado de usuarios</h1>
<% if notice %>
    <p id="notice"><%= notice %></p>
<% end %>


<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= usuario.email %></td>
        <td><%= link_to 'Show', usuario %></td>
        <td><%= link_to 'Edit', edit_usuario_path(usuario) %></td>
        <td><%= link_to 'Destroy', usuario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Usuario', new_usuario_path %>

app/views/usuarios/modificar_info.html.erb
<div class="container-full">

  <div class="row">

    <div class="col-lg-12 text-center v-center">

      <h1>Modificar Información de Cuenta</h1>

      <br>

      <form class="col-lg-12">

      </form>
      <div><span class="glyphicon glyphicon-screenshot"></span>   <%= link_to "Cambiar Nombre de Cuenta", edit_nombre_path(@usuario), :class => 'btn btn-default' %></div><br>
      <div><span class="glyphicon glyphicon-cog"></span>   <%= link_to "Cambiar Contraseña", '#', :class=>'btn btn-default  ' %></div><br>
      <div><span class="glyphicon glyphicon-envelope"></span>   <%= link_to "Modificar Correo", '#', :class => 'btn btn-default' %></div><br>



  </div>

</div> <!-- /row -->

<div class="row">


</div>

<br><br><br><br><br>

</div>

app/views/usuarios/new.html.erb
<%= render 'form' %>

<!--<%= link_to 'Back', usuarios_path %> -->

app/views/usuarios/registro_inicio.html.erb
<h2>Bienvenido a SHiMed <%= @usuario.nombre %>!</h2>
<p>Selecciona tu tipo de usuario antes de continuar</p>

<%= link_to "Médico", registro_medico_path(@usuario), :class=>"btn btn-default btn-lg btn-block" %>
<%= link_to "Centro de Salud", registro_centro_path(@usuario), :class=>"btn btn-default btn-lg btn-block" %>

app/views/usuarios/show.html.erb
<h1 class="text-center v-center"><%= @usuario.nombre %></h1>
<p>
  <span class="label label-primary">Email:</span>
  <%= @usuario.email %>
</p>
<div class="col-lg-12 text-center v-center">
    <% if @usuario.tipo_usuario == nil %>
        <h2>No has completado tu registro, terminalo entrando en Editar Tipo de Cuenta</h2><br><br>
        <div><span class="glyphicon glyphicon-briefcase"></span>              <%= link_to "Editar Tipo de Cuenta", phase1_path(@usuario), :class => 'btn btn-default' %></div><br>
    <% end %>
</div>

<% if @usuario.tipo_usuario == 1 %>
    <p>
      <strong>Nombre:</strong>
      <%= @usuario.nombre %>
    </p>

    <p>
      <strong>Apellido:</strong>
      <%= @medico.apellido %>
    </p>

    <p>
      <strong>Cedula:</strong>
      <%= @medico.cedula %>
    </p>

    <p>
      <strong>Especialidad:</strong>
      <%= @medico.especialidad %>
    </p>

    <p>
      <strong>Direccion:</strong>
      <%= @medico.direccion %>
    </p>

    <p>
      <strong>Telefono casa:</strong>
      <%= @medico.telefono_casa %>
    </p>

    <p>
      <strong>Telefono celular:</strong>
      <%= @medico.telefono_celular %>
    </p>

    <p>
      <strong>Telefono oficina:</strong>
      <%= @medico.telefono_oficina %>
    </p>

    <p>
      <strong>Sexo:</strong>
      <%= @medico.sexo %>
    </p>

    <p>
      <strong>Fecha nacimiento:</strong>
      <%= @medico.fecha_nacimiento %>
    </p>

    <p>
      <strong>Número Colegio de Medicos:</strong>
      <%= @medico.cmv %>
    </p>

    <p>
      <strong>Curriculum Vitae:</strong>
      <%= @medico.cv %>
    </p>

    <p>
      <strong>Página Web:</strong>
      <%= link_to @medico.url, @medico.url %>
    </p>
    <%= link_to 'Ver Servicios Medicos Ofrecidos', ver_servicios_medicos_path(@medico), { :class=> 'btn btn-lg btn-primary', :style=> 'text: #FFFFFF;' }  %>
<% end %>

<% if @usuario.tipo_usuario == 2 %>
    <p>
      <strong>Nombre de Centro de Salud:</strong>
      <%= @centro_salud.nombre %>
    </p>

    <p>
      <strong>Rif:</strong>
      <%= @centro_salud.rif %>
    </p>

    <p>
      <strong>Descripcion:</strong>
      <%= @centro_salud.descripcion %>
    </p>

    <p>
      <strong>Estado:</strong>
      <%= @centro_salud.estado %>
    </p>

    <p>
      <strong>Ciudad:</strong>
      <%= @centro_salud.ciudad %>
    </p>

    <p>
      <strong>Direccion:</strong>
      <%= @centro_salud.direccion %>
    </p>

    <p>
      <strong>Direccion fiscal:</strong>
      <%= @centro_salud.direccion_fiscal %>
    </p>

    <p>
      <strong>Telefono:</strong>
      <%= @centro_salud.telefono %>
    </p>

    <p>
      <strong>Fax:</strong>
      <%= @centro_salud.fax %>
    </p>

    <p>
      <strong>Sitio web:</strong>
      <%= @centro_salud.sitio_web %>
    </p>

<% end %>


<!--<%= link_to 'Edit', edit_usuario_path(@usuario) %> |
<%= link_to 'Back', usuarios_path %>-->