config/routes.rb
Rails.application.routes.draw do
  resources :usuarios

  resources :medicos

  get 'static/index'

  resources :centro_saluds

  root 'static#index', as: 'static'

  get '/medic_register/:id' => 'medicos#new', as: :registro_medico
  get '/centro_register/:id' => 'centro_saluds#new', as: :registro_centro
  get '/ad%/xas/159/qw%/:id' => 'usuarios#registro_inicio', as: :phase1
  get '/oq/q2s/2/qw%/:remember_token' => 'usuarios#pre_process', as: :pre_pro
  get '/usuarios/registro_inicio'
  get '/emailcheck/:id', to: 'static#emailcheck', as: :mailcheck

  post '/sessions/' => 'sessions#create', as: :sessions
  delete '/signout/' => 'sessions#destroy', as: :sessions_destroy
  get '/error/' => 'sessions#signin_error', as: :session_error
  match '/signin', to: 'sessions#signin', via: 'get'

  get '/ajustes/:remember_token' => 'usuarios#ajustes', as: :ajustes
  get '/ajustes/mod_info_cuenta/:id' => 'usuarios#modificar_info', as: :modificar_info
  get '/austes/mod_info_cuenta/edit_nombre/:id' => 'usuarios#edit_nombre', as: :edit_nombre
  get '/mod_info_cuenta/' => 'static#info_cambiada', as: :info_cambiada

  get '/new_servicios_medicos/:id' => 'medicos#registrar_servicios_medicos', as: :registrar_servicios_medicos
  get '/servicios_medicos/:id' => 'medicos#ver_servicios_medicos', as: :ver_servicios_medicos
  get '/editar_servicios_medicos/:id' => 'medicos#editar_servicios_medicos', as: :editar_servicios_medicos

  get '/already_registered/' => 'static#already_registered', as: :already_registered

end

app/models/medico.rb
#encoding: utf-8
class Medico < ActiveRecord::Base
  belongs_to :usuario


  enum sexo: { Masculino: 0, Femenino: 1}
  validates :usuario_id, presence: true, :uniqueness => { :message => "Ya estas registrado como Médico"}

  validates :apellido, format: {
      with: /(\A[a-zA-ZñÑáéíóúÁÉÍÓÚäëïöüÄËÏÖÜßÇç´][a-zA-ZñÑáéíóúÁÉÍÓÚßÇç´ -']+\Z)/, :message => 'Apellido no puede contener números ni caracteres especiales'
  }
  validates :apellido, length: {in: 2..25, :message => "Apellido no debe ser mayor a 25 caracteres" }
  validates :apellido,  :presence => { :message => "El campo Apellido es obligatorio" }

  validates :cedula, format: {
      with: /(\A([VE\s]+)-[0-9]{1,15}\z)/i , :message => "Cédula debe ir con el formato V/E-XXXXXXX"
  }
  validates :cedula, :uniqueness => { :message => "Esa Cédula ya existente"}
  validates :cedula, :presence => { :message => "El campo Cedula es obligatorio" }

  validates :especialidad, format: {
      with: /(\A[a-zA-ZñÑáéíóúÁÉÍÓÚäëïöüÄËÏÖÜßÇç´][a-zA-ZñÑáéíóúÁÉÍÓÚßÇç´ -']+\Z)/, :message => 'Especialidad no puede contener números ni caracteres especiales'
  }
  validates :especialidad, :presence => { :message => "El campo Especialidad es obligatorio" }

  validates :telefono_casa, format: {
      with: /(\A^([0-9]{4,6})+-([0-9]{7,9})\z)/i, :message => "Teléfono de Casa debe ir con el formato XXXX-XXXXXXX y solo puede contener números"
  }, :allow_blank => true

  validates :telefono_celular, format: {
      with: /(\A^([0-9]{4,6})+-([0-9]{7,9})\z)/i, :message => "Teléfono Celular debe ir con el formato XXXX-XXXXXXX y solo puede contener números"
  }, :allow_blank => true

  validates :telefono_oficina, format: {
      with: /(\A([0-9]{4,6})+-([0-9]{7,9})\z)/i, :message => "Teléfono Oficina debe ir con el formato XXXX-XXXXXXX y solo puede contener números"
  }, :allow_blank => true

  validates :telefono_consultorio, format: {
      with: /(\A([0-9]{4,6})+-([0-9]{7,9})\z)/i, :message => "Teléfono Consultorio debe ir con el formato XXXX-XXXXXXX y solo puede contener números"
  }, :allow_blank => true

  validates :sexo, :presence => { :message => "El campo Sexo es obligatorio" }

  validates :cmv, format: {
      with: /(\A^[0-9]{4,10}\z)/i, :message => 'El número de colegio de Médicos no puede contener letras ni caracteres especiales y debe contener una longitud de 4 a 10 caracteres'
  }
  validates :cmv, :presence => { :message => "El campo CMV es obligatorio" }




end

app/controllers/medicos_controller.rb
class MedicosController < ApplicationController
  before_action :set_medico, only: [:show, :edit, :update, :destroy, :ver_servicios_medicos, :registrar_servicios_medicos, :editar_servicios_medicos]

  # GET /medicos
  # GET /medicos.json

  def registro_medico
    @usuario=Usuario.find_by(params[:id])
  end

  def index
    @medicos = Medico.all
  end

  # GET /medicos/1
  # GET /medicos/1.json
  def show
    @medico = Medico.find(params[:id])
    @usuario = Usuario.find(@medico.usuario_id)
  end

  # GET /medicos/new
  def new
    @medico = Medico.find_by_usuario_id(params[:id])
    @medico = Medico.new
  end

  # GET /medicos/1/edit
  def edit
  end

  # POST /medicos
  # POST /medicos.json
  def create
    @medico = Medico.new(medico_params)
    @medico.usuario_id = params[:usuario_id_aux]
    @usuario = Usuario.find(params[:usuario_id_aux])
    @medico.nombre=@usuario.nombre
    respond_to do |format|
      if not_update_tipo_usuario
        if @medico.save
          @usuario.tipo_usuario = 1
          @usuario.rol_id = @medico.id
          if @usuario.save
            format.html { redirect_to @medico }
          else
            @medico.delete
            @usuario.errors.each do |name_, erro|
              flash[name_] = erro
            end
            format.html { redirect_to registro_medico_path(@usuario) }
          end
        else
          @medico.errors.each do |name_, erro|
            flash[name_] = erro
          end
          format.html { redirect_to registro_medico_path(@usuario) }
        end
      else
        @usuario.errors.each do |name_, erro|
          flash[name_] = erro
        end
        format.html { redirect_to already_registered_path}
      end

    end
  end

  def registro_medico

  end

  # PATCH/PUT /medicos/1
  # PATCH/PUT /medicos/1.json
  def update
    respond_to do |format|
      if @medico.update(medico_params)
        format.html { redirect_to info_cambiada_path }
      else
        @medico.errors.each do |name_, erro|
          flash[name_] = erro
        end
       format.html { render :edit }
      end
    end
  end

  # DELETE /medicos/1
  # DELETE /medicos/1.json
  def destroy
    @medico.destroy
    respond_to do |format|
      format.html { redirect_to medicos_url, notice: 'Medico was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def registrar_servicios_medicos

  end

  def editar_servicios_medicos
  end

  def ver_servicios_medicos
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_medico
      @medico = Medico.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def medico_params
      params.require(:medico).permit(:email, :nombre, :apellido, :cedula, :direccion, :telefono_casa, :telefono_celular, :telefono_oficina, :sexo, :fecha_nacimiento, :especialidad, :cmv, :cv, :url, :centro_salud, :servicio_medico, :modalidad_consulta, :horario_consulta, :precio_consulta, :telefono_consultorio)
    end

    def servicios_medicos_params
      params.require(:medico).permit(:centro_salud, :servicio_medico, :modalidad_consulta, :horario_consulta, :precio_consulta, :telefono_consultorio)
    end
end

app/helpers/medicos_helper.rb
module MedicosHelper
end

app/views/medicos/_form.html.erb
<%- if flash.any? %>
    <%- flash.keys.each do |flash_key| %>
        <%- next if flash_key.to_s == 'timedout' %>
        <div class="alert alert-success <%= flash_key %>">
          <a class="close" data-dismiss="alert" href="#"> x</a>
          <%= flash.discard(flash_key) %>
        </div>
    <%- end %>
<%- end %>

<%= form_for(@medico) do |f| %>
    <% if @medico.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@medico.errors.count, "error") %> prohibited this medico from being saved:</h2>

          <ul>
            <% @medico.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :apellido %><br>
      <%= f.text_field :apellido %>
    </div>
    <div class="field">
      <%= f.label :cedula %><br>
      <%= f.text_field :cedula %>
    </div>
    <div class="field">
      <%= f.label :especialidad %><br>
      <%= f.text_field :especialidad %>
    </div>
    <div class="field">
      <%= f.label :direccion %><br>
      <%= f.text_area :direccion %>
    </div>
    <div class="field">
      <%= f.label :telefono_casa %><br>
      <%= f.text_field :telefono_casa %>
    </div>
    <div class="field">
      <%= f.label :telefono_celular %><br>
      <%= f.text_field :telefono_celular %>
    </div>
    <div class="field">
      <%= f.label :telefono_oficina %><br>
      <%= f.text_field :telefono_oficina %>
    </div>
    <div class="field">
      <%= f.label :sexo %><br>
      <%= f.select :sexo, options_for_select(['Masculino', 'Femenino']) %>
    </div>
    <div class="field">
      <%= f.label :fecha_nacimiento %><br>
      <%= f.date_select :fecha_nacimiento %>
    </div>
    <div class="field">
        <%= f.label 'Número de Colegio de Médicos' %><br>
        <%= f.text_field :cmv %>
    </div>
    <div class="field">
      <%= f.label "Curriculum Vitae:" %><br>
      <%= f.text_area :cv, rows: 8 %>
    </div>
    <div class="field">
      <%= f.label :url %><br>
      <%= f.text_field :url %>
    </div>
    <%= hidden_field_tag 'usuario_id_aux', params[:id] %>

    <div class="actions">
      <%= f.submit "Registro de Médico", data: { confirm: 'Seguro que desea guardar los cambios?' } %>
    </div>
<% end %>

app/views/medicos/_form_servicios_medicos.html.erb
<%- if flash.any? %>
    <%- flash.keys.each do |flash_key| %>
        <%- next if flash_key.to_s == 'timedout' %>
        <div class="alert alert-success <%= flash_key %>">
          <a class="close" data-dismiss="alert" href="#"> x</a>
          <%= flash.discard(flash_key) %>
        </div>
    <%- end %>
<%- end %>

<%= form_for(@medico) do |f| %>
<!--    <% if @medico.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@medico.errors.count, "error") %> prohibited this medico from being saved:</h2>

          <ul>
            <% @medico.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>-->

    <div class="field">
      <%= f.label :centro_salud %><br>
      <%= f.text_field :centro_salud %>
    </div>
    <div class="field">
      <%= f.label :servicio_medico %><br>
      <%= f.text_field :servicio_medico %>
    </div>
    <div class="field">
      <%= f.label :modalidad_consulta %><br>
      <%= f.text_field :modalidad_consulta %>
    </div>
    <div class="field">
      <%= f.label :horario_consulta %><br>
      <%= f.text_area :horario_consulta, rows: 10 %>
    </div>
    <div class="field">
      <%= f.label :precio_consulta %><br>
      <%= f.text_field :precio_consulta %>
    </div>
    <div class="field">
      <%= f.label :telefono_consultorio %><br>
      <%= f.text_field :telefono_consultorio %>
    </div>
    <%= hidden_field_tag 'usuario_id_aux', params[:id] %>

    <div class="actions">
      <%= f.submit "Actualizar Servicios Médicos", data: { confirm: 'Seguro que desea guardar los cambios?' }%>
    </div>
<% end %>

app/views/medicos/_formedit.html.erb
<%- if flash.any? %>
    <%- flash.keys.each do |flash_key| %>
        <%- next if flash_key.to_s == 'timedout' %>
        <div class="alert alert-success <%= flash_key %>">
          <a class="close" data-dismiss="alert" href="#"> x</a>
          <%= flash.discard(flash_key) %>
        </div>
    <%- end %>
<%- end %>

<%= form_for(@medico) do |f| %>
<!--  <% if @medico.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@medico.errors.count, "error") %> prohibited this medico from being saved:</h2>

      <ul>
      <% @medico.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>-->

  <div class="field">
    <%= f.label :apellido %><br>
    <%= f.text_field :apellido %>
  </div>
  <div class="field">
    <%= f.label :cedula %><br>
    <%= f.text_field :cedula %>
  </div>
  <div class="field">
    <%= f.label :especialidad %><br>
    <%= f.text_field :especialidad %>
  </div>
  <div class="field">
    <%= f.label :direccion %><br>
    <%= f.text_area :direccion %>
  </div>
  <div class="field">
    <%= f.label :telefono_casa %><br>
    <%= f.text_field :telefono_casa %>
  </div>
  <div class="field">
    <%= f.label :telefono_celular %><br>
    <%= f.text_field :telefono_celular %>
  </div>
  <div class="field">
    <%= f.label :telefono_oficina %><br>
    <%= f.text_field :telefono_oficina %>
  </div>
  <div class="field">
    <%= f.label :sexo %><br>
    <%= f.select :sexo, options_for_select([['Masculino'], ['Femenino']]) %>
  </div>
  <div class="field">
    <%= f.label :fecha_nacimiento %><br>
    <%= f.date_select :fecha_nacimiento %>
  </div>
  <div class="field">
    <%= f.label 'Número de Colegio de Médicos' %><br>
    <%= f.text_field :cmv %>
  </div>
  <div class="field">
    <%= f.label "Curriculum Vitae:" %><br>
    <%= f.text_area :cv, rows: 8 %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <%= hidden_field_tag 'usuario_id_aux', params[:id] %>

  <div class="actions">
    <%= f.submit "Actualizar Perfil", data: { confirm: 'Seguro que desea guardar los cambios?' }%>
  </div>
<% end %>

app/views/medicos/edit.html.erb
<h1>Modificar Perfíl de Médico</h1>

<%= render 'formedit' %>

app/views/medicos/editar_servicios_medicos.html.erb
<h1>Editar Servicios Médicos</h1>

<%= render 'form_servicios_medicos' %>

app/views/medicos/index.html.erb
<h1>Directorio Médico</h1>

<table class="table table-striped table-bordered table-condensed">
  <tbody>
    <tr>
      <td><b>Nombre y Apellido</b></td>
      <td><b>Especialidad</b></td>
      <td><b>Teléfono Celular</b></td>
      <td><b>Curriculum Vitae</b></td>
      <td><b>Página Web</b></td>
    </tr>
    <% @medicos.each do |medico| %>
      <tr>
        <td><%= link_to medico.nombre+" "+medico.apellido, medico, :class => 'h4' %></td>
        <td><%= medico.especialidad %></td>
        <td><%= medico.telefono_celular %></td>
        <td><%= truncate(strip_tags(medico.cv), length: 100) %></td>
        <td><a href="<%= medico.url %>"><%= medico.url %></a></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!-- <%= link_to 'Nuevo Medico', new_medico_path %> -->

app/views/medicos/new.html.erb
<h1>Registro de Médico</h1>

<%= render 'form' %>

app/views/medicos/show.html.erb
<h1 class="text-center v-center"><%= @medico.nombre %></h1>
<p>
  <strong>Nombre:</strong>
  <%= @medico.nombre %>
</p>

<p>
  <strong>Apellido:</strong>
  <%= @medico.apellido %>
</p>

<p>
  <strong>Cedula:</strong>
  <%= @medico.cedula %>
</p>

<p>
  <strong>Especialidad:</strong>
  <%= @medico.especialidad %>
</p>

<p>
  <strong>Direccion:</strong>
  <%= @medico.direccion %>
</p>

<p>
  <strong>Telefono casa:</strong>
  <%= @medico.telefono_casa %>
</p>

<p>
  <strong>Telefono celular:</strong>
  <%= @medico.telefono_celular %>
</p>

<p>
  <strong>Telefono oficina:</strong>
  <%= @medico.telefono_oficina %>
</p>

<p>
  <strong>Sexo:</strong>
  <%= @medico.sexo %>
</p>

<p>
  <strong>Fecha nacimiento:</strong>
  <%= @medico.fecha_nacimiento %>
</p>

<p>
  <strong>Número Colegio de Medicos:</strong>
  <%= @medico.cmv %>
</p>

<p>
  <strong>Curriculum Vitae:</strong>
  <%= @medico.cv %>
</p>

<p>
  <strong>Página Web:</strong>
  <%= link_to @medico.url, @medico.url %>
</p>
<br>

<%= link_to 'Atras', medicos_path, :class=> 'btn btn-default' %>
<%= link_to 'Ver Servicios Medicos Ofrecidos', ver_servicios_medicos_path(@medico), { :class=> 'btn btn-lg btn-primary', :style=> 'text: #FFFFFF;' }  %>

app/views/medicos/ver_servicios_medicos.html.erb
<h1 class="text-center v-center">Servicios - Médico <%= @medico.nombre %></h1>

<p>
  <strong>Centro de Salud:</strong>
  <%= @medico.centro_salud %>
</p>

<p>
  <strong>Servicio Médico Ofrecido:</strong>
  <%= @medico.servicio_medico %>
</p>

<p>
  <strong>Modalidad de Consulta:</strong>
  <%= @medico.modalidad_consulta %>
</p>

<p>
  <strong>Horario de Consulta:</strong>
  <%= @medico.horario_consulta %>
</p>

<p>
  <strong>Precio de Consulta:</strong>
  <%= @medico.precio_consulta %>
</p>

<p>
  <strong>Teléfono Consultorio:</strong>
  <%= @medico.telefono_consultorio %>
</p>

<%= link_to 'Atras', medico_path(@medico), :class=> 'btn btn-default' %>