config/routes.rb
Rails.application.routes.draw do
  resources :usuarios

  resources :medicos

  get 'static/index'

  resources :centro_saluds

  root 'static#index', as: 'static'

  get '/medic_register/:id' => 'medicos#new', as: :registro_medico
  get '/centro_register/:id' => 'centro_saluds#new', as: :registro_centro
  get '/ad%/xas/159/qw%/:id' => 'usuarios#registro_inicio', as: :phase1
  get '/oq/q2s/2/qw%/:remember_token' => 'usuarios#pre_process', as: :pre_pro
  get '/usuarios/registro_inicio'
  get '/emailcheck/:id', to: 'static#emailcheck', as: :mailcheck

  post '/sessions/' => 'sessions#create', as: :sessions
  delete '/signout/' => 'sessions#destroy', as: :sessions_destroy
  get '/error/' => 'sessions#signin_error', as: :session_error
  match '/signin', to: 'sessions#signin', via: 'get'

  get '/ajustes/:remember_token' => 'usuarios#ajustes', as: :ajustes
  get '/ajustes/mod_info_cuenta/:id' => 'usuarios#modificar_info', as: :modificar_info
  get '/austes/mod_info_cuenta/edit_nombre/:id' => 'usuarios#edit_nombre', as: :edit_nombre
  get '/mod_info_cuenta/' => 'static#info_cambiada', as: :info_cambiada

  get '/new_servicios_medicos/:id' => 'medicos#registrar_servicios_medicos', as: :registrar_servicios_medicos
  get '/servicios_medicos/:id' => 'medicos#ver_servicios_medicos', as: :ver_servicios_medicos
  get '/editar_servicios_medicos/:id' => 'medicos#editar_servicios_medicos', as: :editar_servicios_medicos

  get '/already_registered/' => 'static#already_registered', as: :already_registered

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>SHiMed</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller.controller_name %>">
    <!-- Site header and navigation -->
    <header class="top" role="header">
        <div class="container">
           <!-- <a href="#" class="navbar-brand pull-left"> --><%= link_to "SHiMed", static_path, :class => 'navbar-brand pull-left' %>
               <!--SHiMed-->
            <!--</a>-->
            <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="glyphicon glyphicon-align-justify"></span>
            </button>
            <nav class="navbar-collapse collapse" role="navigation">
                <ul class="navbar-nav nav">
                    <li><%= link_to "Inicio", static_index_path, :class => 'a' %></li>
                    <li><%= link_to "Directorio Médico", medicos_path, :class => 'a'%></li>
                    <li><%= link_to "Directorio de Centros de Salud", centro_saluds_path, :class=>'a' %></li>
                    <li>
                      <% if signed_in? %>
                          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= @current_usuario.nombre %><b class="caret"></b></a>
                          <ul class="dropdown-menu" style = 'color: black'>
                            <li><%= link_to "Perfíl", current_usuario  %></li>
                            <li><%= link_to "Ajustes", ajustes_path(@current_usuario.remember_token) ,:class=>'A' %></li>
                            <li class="divider"></li>
                            <li><%= link_to "Cerrar Sesión", sessions_destroy_path, method: "delete" %></li>
                          </ul>
                       <% else %>
                          <li><%= link_to "Registro", new_usuario_url, :class=>'a' %></li>
                          <li><%= link_to "Iniciar Sesión", signin_path, :class => 'a' %></li>
                       <% end %>
                    </li>
                </ul>
            </nav>
        </div>
    </header>
    <!-- Site banner -->
    <div class="banner">
      <div class="container">
        <h1>SHiMed - Red de centros de salud y citas médicas</h1>
        <p>Una red para hacerte la vida mas fácil.</p>
      </div>
    </div>

    <!-- Middle content section -->
    <div class="middle">
      <div class="container">
        <div class="col-lg">
          <%= yield %>
        </div>
        <div class="col-md-3">
         <!-- <h2>Recursos</h2>
          <ul class="nav nav-pills nav-stacked">
            <li><a href="http://www.mpps.gob.ve/" target="_blank">Ministerio del Poder Popular para la Salud</a></li>
            <li><a href="http://www.intt.gob.ve/intt/" target="_blank">INTT</a></li>
            <li><a href="http://iahula.merida.gob.ve/" target="_blank">IHULA</a></li>
            <li><a href="http://www.ivss.gov.ve/" target="_blank">Instituto Venezulano de los Seguros Sociales</a></li>
            <li><a href="http://amzn.to/1oXAbu6" target="_blank">US: HTML & CSS: Design and Build Web Sites</a></li>
            <li><a href="http://amzn.to/1lESF2w" target="_blank">US: Bootstrap Site Blueprints</a></li>
          </ul>
        </div>-->
        </div>
      </div>
    </div>

    <!-- Site footer -->
    <div class="bottom">
      <div class="container">
        <div class="col-md-4">
          <h3><span class="glyphicon glyphicon-user"></span> Ricardo Xavier Graterol</h3>
          <p>Desarrollador de software.</p>
        </div>
        <div class="col-md-4">
          <h3><span class="glyphicon glyphicon-tower"></span> Biosoft C.A.</h3>
          <p>Ingeniería y desarrollo de software.</p>
        </div>
        <div class="col-md-4">
        </div>
      </div>
    </div>
      <script src="includes/jquery/jquery-2.1.0.min.js"></script>
      <script src="includes/bootstrap/js/bootstrap.min.js"></script>

</body>
</html>